version: '3.3'
services:
  # Nginx Container - Reserve Proxy
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - server
    ports:
      - 8080:8080
  # Server Container
  server:
    build: server
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_HOSTNAME: meinecooledb
    links:
      - meinecooledb
    depends_on:
      - meinecooledb
    # Scale: auf 3 definiert, somit werden 3 Server Container erstellt
    scale: 3
  # Datenbank Container
  meinecooledb:
    build: db
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
  # Phpmyadmin Container, erreichbar durch den Port 8085. Dort können Änderungen an der Datenbank vorgenommen werden.
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: meinecooledb